services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
